<?php

namespace Acme\Bundle\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function addOrder($data, $customer_id){
       $sql="INSERT INTO symfony.`order` SET customer_id=".(int)$customer_id.", shipping_address='".$data['address']."', date_added='".date("Y/m/d")."', date_modified='', status_id=1, total_price=".$data['totalPrice'];
       
       $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
        
    	return $conn->lastInsertId();
    }
    public function findAllOrder()
    {
        $sql = "SELECT * FROM symfony.`order` od INNER JOIN symfony.`customer` ct ON od.customer_id=ct.customer_id ORDER BY email ASC";
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
        return $stmt->fetchAll();
    }
    public function deleteOrderById($order_id){
        $sql = "DELETE FROM symfony.`order` WHERE id=".$order_id;
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
    }
    
    public function findOrderByOrderId($order_id){
        $sql = "SELECT * FROM symfony.`order` WHERE id=".$order_id;
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
        return $stmt->fetchAll();
    }
}
