Acme\Bundle\BlogBundle\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: Acme\Bundle\BlogBundle\Entity\Repository\CustomerRepository
    id:
        customerId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: customer_id
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
        address:
            type: string
            nullable: true
            length: 255
            fixed: false
        firstname:
            type: string
            nullable: false
            length: 20
            fixed: false
        lastname:
            type: string
            nullable: false
            length: 20
            fixed: false
        phone:
            type: string
            nullable: true
            length: 20
            fixed: false
    lifecycleCallbacks: {  }
