Acme\Bundle\BlogBundle\Entity\OrderDetail:
    type: entity
    table: order_detail
    repositoryClass: Acme\Bundle\BlogBundle\Entity\Repository\OrderDetailRepository
    indexes:
        fk_order_detail_1_idx:
            columns:
                - order_id
        fk_order_detail_1_idx1:
            columns:
                - product_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: false
            unsigned: false
        price:
            type: decimal
            nullable: true
            precision: 20
            scale: 0
    manyToOne:
        order:
            targetEntity: Order
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                order_id:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Product
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
