<?php

namespace Acme\Bundle\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    public function addCustomer($data){
    	$sql = "INSERT INTO symfony.`customer` SET email='".$data['email']."' "
    	.", firstname='".$data['firstname']."' "
    	.", lastname='".$data['lastname']."' ";
    	if($data['address']){
    		$sql .= ", address='".$data['address']."' ";
    	}
    	if($data['phone']){
    		$sql .= ", phone='".$data['phone']."' ";
    	}
    	$conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
    	return $conn->lastInsertId();
    }

    public function getCustomerByEmail($email){
    	$stmt = $this->getEntityManager()
        ->getConnection()
        ->prepare("SELECT * FROM symfony.`customer` WHERE email='".$email."'");
        $stmt->execute();
        return $stmt->fetch();
    }
    
    public function findCustomerById($customer_id){
        $sql = "SELECT * FROM symfony.`customer` WHERE customer_id=".$customer_id;
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
    	return $stmt->fetch();
    }
}
