<?php

namespace Acme\Bundle\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailRepository extends EntityRepository
{
    public function addOrderDetail($product_id, $product, $order_id){
    	$sql = "INSERT INTO symfony.`order_detail` SET order_id=".$order_id." "
    	.", product_id=".$product_id." "
    	.", quantity=".$product['quantity']." ";
    	if($product['price']){
    		$sql .= ", price=".($product['quantity']*$product['price'])." ";
    	}
    	$conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
    }
    
    public function deleteOrderDetailByOrderId($order_id){
        $sql = "DELETE FROM symfony.`order_detail` WHERE order_id=".$order_id;
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
    }
    
    public function findOrderDetailByOrderId($order_id){
        $sql = "SELECT * FROM symfony.`order_detail` od INNER JOIN symfony.`order` o ON od.order_id=o.id WHERE order_id=".$order_id;
        
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
        return $stmt->fetchAll();
    }
}
