<?php

namespace Acme\Bundle\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function addOrder($data, $customer_id){
        $order = new Order();
        $order->setCustomer($customer_id);
        $order->setShippingAddress($data['address']);
        $order->setDateAdded(date("Y/m/d"));
        $order->setDateModified('');
        $order->setStatusId(1);
        $order->setTotalPrice($data['totalPrice']);
        
        $em = $this->getEntityManager();
        $em->persist($order);
        $em->flush();
        
    	return $order->getId();
    }
    public function findAllOrder()
    {
        $sql = "SELECT * FROM symfony.`order` od INNER JOIN symfony.`customer` ct ON od.customer_id=ct.customer_id ORDER BY email ASC";
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
        return $stmt->fetchAll();
    }
    public function deleteOrderById($order_id){
        $sql = "DELETE FROM symfony.`order` WHERE id=".$order_id;
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
    }
    
    public function findOrderByOrderId($order_id){
        $sql = "SELECT * FROM symfony.`order` WHERE id=".$order_id;
        $conn = $this->getEntityManager()->getConnection();
    	$stmt = $conn->prepare($sql);
    	$stmt->execute();
        return $stmt->fetchAll();
    }
}
