<?php

namespace Acme\Bundle\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    
    public function updateProduct($product, $data){
        
        if($data['description']){
            $product->setDescription($data['description']);
        }
        if($data['image_url']){
            $product->setImageUrl($data['image_url']);
        }
        if($data['quantity']){
            $product->setQuantity($data['quantity']);
        }
        if($data['category_id']){
            $product->setCategory($data['category_id']);
        }
        if($data['price']){
            $product->setPrice($data['price']);
        }
        $em = $this->getEntityManager();
        $em->flush();
    }
}
